# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /fs/student/ashishvyas/Downloads/Lab2A/Lab1B_handout/Lab1B/Lab1B.srcs/sources_1/bd/system/ip/system_axi_gpio_0_7/system_axi_gpio_0_7.xci
# IP: The module: 'system_axi_gpio_0_7' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /fs/student/ashishvyas/Downloads/Lab2A/Lab1B_handout/Lab1B/Lab1B.srcs/sources_1/bd/system/ip/system_axi_gpio_0_7/system_axi_gpio_0_7_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_axi_gpio_0_7'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /fs/student/ashishvyas/Downloads/Lab2A/Lab1B_handout/Lab1B/Lab1B.srcs/sources_1/bd/system/ip/system_axi_gpio_0_7/system_axi_gpio_0_7_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_axi_gpio_0_7'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /fs/student/ashishvyas/Downloads/Lab2A/Lab1B_handout/Lab1B/Lab1B.srcs/sources_1/bd/system/ip/system_axi_gpio_0_7/system_axi_gpio_0_7.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_axi_gpio_0_7'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /fs/student/ashishvyas/Downloads/Lab2A/Lab1B_handout/Lab1B/Lab1B.srcs/sources_1/bd/system/ip/system_axi_gpio_0_7/system_axi_gpio_0_7.xci
# IP: The module: 'system_axi_gpio_0_7' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /fs/student/ashishvyas/Downloads/Lab2A/Lab1B_handout/Lab1B/Lab1B.srcs/sources_1/bd/system/ip/system_axi_gpio_0_7/system_axi_gpio_0_7_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_axi_gpio_0_7'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /fs/student/ashishvyas/Downloads/Lab2A/Lab1B_handout/Lab1B/Lab1B.srcs/sources_1/bd/system/ip/system_axi_gpio_0_7/system_axi_gpio_0_7_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_axi_gpio_0_7'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /fs/student/ashishvyas/Downloads/Lab2A/Lab1B_handout/Lab1B/Lab1B.srcs/sources_1/bd/system/ip/system_axi_gpio_0_7/system_axi_gpio_0_7.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_axi_gpio_0_7'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
